name = "Ising2D"
uuid = "b6538906-b295-4c3d-8ed2-7ee255f159dd"
authors = ["UgoMire <ugomire@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
